### ISSUE TITLE
Add logger.debug if all health checks passed

### ISSUE THREAD

**Issue by hf-kklein** [ateliedocodigo/py-healthcheck#32]
As of now only [failures](https://github.com/ateliedocodigo/py-healthcheck/blob/e6205bdcc32099d12cda6eba172b4a801104448f/healthcheck/healthcheck.py#L140) and [exceptions](https://github.com/ateliedocodigo/py-healthcheck/blob/e6205bdcc32099d12cda6eba172b4a801104448f/healthcheck/healthcheck.py#L130) are logged.

Could we also log passing tests with a low log level, e.g. using `logger.debug`?

**Comment by luiscoms** [comment]
Hi @hf-kklein feel free to contribute and add this logs.

If you want to log for every check, you can add logger here https://github.com/ateliedocodigo/py-healthcheck/blob/develop/healthcheck/healthcheck.py#L130

If you want a complete summary, add a log here https://github.com/ateliedocodigo/py-healthcheck/blob/develop/healthcheck/healthcheck.py#L140

**Comment by hf-kklein** [comment]
Hi @luiscoms ,
thanks for your input. I opened PR #35 based on your suggestions.
